### ISSUE TITLE
EPiServer 10 Compatibility for IContentVersionRepository

### ISSUE THREAD

**Issue by stgaup** [skjelbek/block-breadcrumbs#2]
Hi, I suggest you change the code in BlockBreadcrums.ContentExtensions since it does not compile any more when using the new version of EPiServer. 

In the breaking changes for Episerver 10, this is writen:
CMS-3153 - IContentVersionRepository List methods have been consolidated into one. PageVersion is obsoleted.

The code is not backward compatible.

I have made a pull request.

Old version of code:

>        private static ContentVersion LastVersion(this IContent content)
>        {
>            var versionRep = ServiceLocator.Current.GetInstance<IContentVersionRepository>();
>            var lastVersion = versionRep.List(content.ContentLink).LastOrDefault();
>            return lastVersion;
>        }

My suggested new version:

>        private static ContentVersion LastVersion(this IContent content)
>        {
>            //Changed in EPi 10: CMS-3153 - IContentVersionRepository List methods have been consolidated into one. PageVersion is obsoleted.
>            //new signature: IEnumerable<ContentVersion> List(VersionFilter filter, int startIndex, int maxRows, out int totalCount);
>            var versionsAvailable = 0;
>            var versionRep = ServiceLocator.Current.GetInstance<IContentVersionRepository>();
>            var lastVersion = versionRep.List(
>                new VersionFilter()
>                {
>                    Statuses = new List<VersionStatus> { VersionStatus.Published },
>                    ContentLink = content.ContentLink
>                }, 0, 20, out versionsAvailable).LastOrDefault();
>            return lastVersion;
>        }

**Comment by skjelbek** [comment]
Hi,

Thanks for the PR! However, your suggested implementation only retrieves the versions that are published. The point of this method is to retrieve all versions, regardless of status, and select the latest one. I use that method to check whether the block is being used in a yet-to-be-published page or block. Your suggestion will not show the breadcrumb in a block when adding that block to a contentarea without publishing the page/block owning that contentarea.

I propose the following code instead:

``` csharp
private static ContentVersion LastVersion(this IContent content)
{
     var versionRep = ServiceLocator.Current.GetInstance<IContentVersionRepository>();
     var lastVersion = versionRep.List(content.ContentLink).OrderBy(v => v.Saved).LastOrDefault();
     return lastVersion;
}
```

The List method accepting a ContentReference is not deprecated, it's just moved to a different class (it's an extension method in `EPiServer.Core.IContentVersionRepositoryExtensions`).

I'll accept your PR and ship an updated release of the nuget as soon as we both agree :)

**Comment by skjelbek** [comment]
Fixed in v.1.3

**Comment by stgaup** [comment]
Hi, and thank you! 
I will update my code with your solution.

**Comment by stgaup** [comment]
And sorry for the late response.
